### ISSUE TITLE
Remove null for $instantiator in ProxyFactory::constructor

### ISSUE THREAD

**Issue by vjik** [cycle/proxy-factory#13]
Instantiator required for ProxyFactory.
https://github.com/cycle/proxy-factory/blob/fd8e7d5c4d67b6ad8ae13d83b156cf07ce535f8a/src/Promise/ProxyFactory.php#L60

---

I try use cycle/proxy-factory with yii2, but yii2 container don't support DI for constructor arguments with default null.

**Comment by vvval** [comment]
@vjik and what about the last 2 arguments for `materializer` and `names`?

**Comment by vvval** [comment]
@vjik check please the PR, will it work for you?

**Comment by vjik** [comment]
Yes, this PR fine work for me. Thank you!

I hope in next release Yii2 will be added to DI support parameters with default values for constructor (https://github.com/yiisoft/yii2/issues/18304). Fix Yii2 will allow set custom `instantiator` and `materializer` and `names` for `ProxyFactory`.
