### ISSUE TITLE
[PHP8] Add support for union types in methods

### ISSUE THREAD

**Issue by sheronov** [cycle/proxy-factory#17]
I want to use in my entity classes methods smth like this:
```
public function setProperties(array|string $properties) : self
{
    $this->properties = is_string($properties) ? $properties : json_encode($properties);
    return $this;
}
```

When a model loaded directly (fetchOne(), findByPk() and etc) everything is fine.

But when I want to use lazy load of relations (it happens through promises classes) I receive a 500 error with the message 
> Call to undefined method ReflectionUnionType::getName() in ... /Promise/Declaration/Extractor/Methods.php at line 215

I also use union types in class properties, but with them all seems good.

**Comment by sheronov** [comment]
Found one more problem in the same method.

Until union types are not supported I tried to use **mixed** type for methods. 

The problem is again linked to a ReflectionType in the defineType method.
When you check type for allowsNull [here](https://github.com/cycle/proxy-factory/blob/master/src/Promise/Declaration/Extractor/Methods.php#L222) for _mixed_ type it'll return true; 

After that **?mixed** string goes to nikic/php-parser to the normalizeType method, which has a [check](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/BuilderHelpers.php#L201) that _mixed type cannot be nullable_  

Sorry if I wrote something strange.
I hope my investigation will help you.

**Comment by vvval** [comment]
First of all we need to check that the type isn't "mixed" where we prepend "?" as a nullable declaration (since it's allows in the type hinting, isn't it?).

And then add the union type support on the exact #215 line.

**Comment by vvval** [comment]
@sheronov I would be very grateful if you add a test with a negative use case so we would easily fix it
